---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: webmap-be-api
  namespace: webmap
spec:
  prefix: /webmap/
  service: treetracker-webmap-api-ambassador-svc
  rewrite: /
  timeout_ms: 0
  cors:
    methods: GET, OPTIONS
    headers:
    - Content-Type
    - Authorization
