---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: webmap-be-api
  namespace: webmap
spec:
  prefix: /webmap/
  service: treetracker-webmap-api-ambassador-svc
  rewrite: /
  timeout_ms: 0
  cors:
    origins: 
    - https://dev.webmap.treetracker.org
    - https://dev.treetracker.org
    - https://test.treetracker.org
    - https://treetracker.org
    - https://ready.treetracker.org
    - https://wallet.treetracker.org
    - https://freetown.treetracker.org
    - https://map.treetracker.org
    - http://localhost:3000
    methods: GET
