name: Webmap Server CI/CD Unstable Branch

on:
  push:
    paths:
    - '**'
    - '.github/workflows/treetracker-webmap-server*'
    branches:
      - unstable

env: 
  project-directory: ./

jobs:
  #  test:
  #   - name: npm clean install
  #    run: npm ci
  #    working-directory: ${{ env.project-directory }}
      #    - name: run ESLint
      # run: npm run lint
      #working-directory: ${{ env.project-directory }}
      #- name: build server project
      #run: npm run build
      #working-directory: ${{ env.project-directory }}
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == 'Greenstand/treetracker-web-map'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm clean install
      run: npm ci
      working-directory: ${{ env.project-directory }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Another step
      run: |
        echo "Branch: ${{ steps.vars.outputs.branch }}"
        echo "Sha: ${{ steps.vars.outputs.sha_short }}"
      
    - name: Build snapshot with git sha and push on merge
      id: docker_build_snapshot_merge
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        push: true
        tags: greenstand/treetracker-webmap-api:${{ steps.vars.outputs.sha_short }}
    - shell: bash
      run: |
        echo '${{ steps.vars.outputs.sha_short }}' > image-tag



  
